/**
 * Danh mục nhóm ngành, dùng cho bộ lọc "Ngành nghề" trên trang tìm việc.
 *
 * Phẳng một tầng, KHÔNG phân cấp: đề tài phục vụ mọi ngành nên một cây ngành
 * đúng chuẩn sẽ có hàng trăm nút, mà bộ lọc chỉ cần đủ để thu hẹp từ vài nghìn
 * tin xuống vài trăm. Ai muốn hẹp hơn thì gõ vào ô tìm kiếm.
 *
 * `keywords` đã ở dạng thường và không dấu, khớp bằng cách tìm chuỗi con trong
 * `title` và `tags` đã chuẩn hoá. Thứ tự trong mảng CÓ nghĩa: mục đứng trước
 * thắng khi một tin khớp nhiều nhóm, nên nhóm nào có từ khoá đặc trưng hơn thì
 * đặt lên trên.
 */
export interface Occupation {
  code: string;
  name: string;
  keywords: string[];
}

export const OCCUPATIONS: Occupation[] = [
  {
    code: 'DATA_AI',
    name: 'Dữ liệu & AI',
    keywords: [
      'data analyst',
      'data engineer',
      'data scientist',
      'phan tich du lieu',
      'khoa hoc du lieu',
      'machine learning',
      'deep learning',
      'artificial intelligence',
      'tri tue nhan tao',
      'business intelligence',
      'bi developer',
      'computer vision',
    ],
  },
  {
    code: 'IT',
    name: 'Công nghệ thông tin',
    keywords: [
      'developer',
      'lap trinh',
      'ky su phan mem',
      'software',
      'engineer',
      'backend',
      'frontend',
      'fullstack',
      'full stack',
      'devops',
      'mobile',
      'android',
      'react',
      'angular',
      'nodejs',
      'node js',
      'java',
      'python',
      'php',
      'golang',
      'dotnet',
      'tester',
      'kiem thu',
      'it support',
      'helpdesk',
      'quan tri he thong',
      'blockchain',
      'nhung',
    ],
  },
  {
    code: 'DESIGN',
    name: 'Thiết kế & Sáng tạo',
    keywords: [
      'designer',
      'thiet ke',
      'ui ux',
      'graphic',
      'do hoa',
      'motion',
      'illustrator',
      'dung phim',
      'editor video',
      'sang tao noi dung',
      'content creator',
      'nhiep anh',
      '3d artist',
    ],
  },
  {
    code: 'MARKETING',
    name: 'Marketing / PR / Quảng cáo',
    keywords: [
      'marketing',
      'truyen thong',
      'quang cao',
      'social media',
      'noi dung',
      'quan he cong chung',
      'thuong hieu',
      'copywriter',
      'media planner',
    ],
  },
  {
    code: 'SALES',
    name: 'Kinh doanh / Bán hàng',
    keywords: [
      'kinh doanh',
      'ban hang',
      'sales',
      'business development',
      'phat trien kinh doanh',
      'account manager',
      'telesales',
      'tu van ban hang',
      'bat dong san',
      'moi gioi',
    ],
  },
  {
    code: 'CUSTOMER',
    name: 'Chăm sóc khách hàng',
    keywords: [
      'cham soc khach hang',
      'customer service',
      'customer support',
      'customer success',
      'tong dai',
      'call center',
      'ho tro khach hang',
      'le tan',
      'receptionist',
    ],
  },
  {
    code: 'FINANCE',
    name: 'Kế toán / Kiểm toán / Tài chính',
    keywords: [
      'ke toan',
      'accountant',
      'kiem toan',
      'audit',
      'tai chinh',
      'finance',
      'thue',
      'ngan hang',
      'banking',
      'tin dung',
      'dau tu',
      'investment',
      'chung khoan',
      'bao hiem',
      'insurance',
      'kiem soat noi bo',
    ],
  },
  {
    code: 'HR',
    name: 'Nhân sự / Hành chính / Pháp chế',
    keywords: [
      'nhan su',
      'human resource',
      'tuyen dung',
      'recruiter',
      'talent acquisition',
      'hanh chinh',
      'thu ky',
      'phap che',
      'phap ly',
      'legal',
      'luat su',
      'tro ly',
    ],
  },
  {
    code: 'MANUFACTURING',
    name: 'Sản xuất / Cơ khí / Điện',
    keywords: [
      'san xuat',
      'production',
      'manufacturing',
      'co khi',
      'mechanical',
      'dien tu',
      'electronic',
      'ky su dien',
      'tu dong hoa',
      'automation',
      'bao tri',
      'maintenance',
      'van hanh may',
      'cong nghiep',
    ],
  },
  {
    code: 'CONSTRUCTION',
    name: 'Xây dựng / Kiến trúc',
    keywords: [
      'xay dung',
      'construction',
      'kien truc',
      'architect',
      'giam sat cong trinh',
      'du toan',
      'thiet ke noi that',
      'civil engineer',
      'chi huy truong',
      'ha tang',
    ],
  },
  {
    code: 'LOGISTICS',
    name: 'Logistics / Xuất nhập khẩu',
    keywords: [
      'logistics',
      'xuat nhap khau',
      'chuoi cung ung',
      'supply chain',
      'kho van',
      'warehouse',
      'thu mua',
      'purchasing',
      'procurement',
      'giao nhan',
      'forwarder',
      'hai quan',
      'van tai',
    ],
  },
  {
    code: 'HEALTHCARE',
    name: 'Y tế / Dược',
    keywords: [
      'bac si',
      'doctor',
      'y ta',
      'nurse',
      'dieu duong',
      'duoc si',
      'pharmacist',
      'trinh duoc vien',
      'y te',
      'healthcare',
      'xet nghiem',
      'nha khoa',
      'phuc hoi chuc nang',
    ],
  },
  {
    code: 'EDUCATION',
    name: 'Giáo dục / Đào tạo',
    keywords: [
      'giao vien',
      'teacher',
      'giang vien',
      'lecturer',
      'gia su',
      'tutor',
      'dao tao',
      'training',
      'giao duc',
      'education',
      'tro giang',
      'tu van du hoc',
    ],
  },
  {
    code: 'HOSPITALITY',
    name: 'Nhà hàng / Khách sạn / Du lịch',
    keywords: [
      'nha hang',
      'khach san',
      'hotel',
      'restaurant',
      'du lich',
      'tourism',
      'dau bep',
      'phuc vu',
      'waiter',
      'barista',
      'bartender',
      'buong phong',
      'huong dan vien',
      'lu hanh',
    ],
  },
  {
    code: 'RETAIL',
    name: 'Bán lẻ / Thương mại điện tử',
    keywords: [
      'ban le',
      'retail',
      'sieu thi',
      'cua hang truong',
      'store manager',
      'thuong mai dien tu',
      'ecommerce',
      'san thuong mai',
      'merchandiser',
    ],
  },
  {
    code: 'AGRICULTURE',
    name: 'Nông / Lâm / Ngư nghiệp',
    keywords: [
      'nong nghiep',
      'agriculture',
      'chan nuoi',
      'thuy san',
      'trong trot',
      'lam nghiep',
      'thu y',
      'nong hoc',
    ],
  },
  {
    code: 'MANUAL',
    name: 'Lao động phổ thông',
    keywords: [
      'lao dong pho thong',
      'cong nhan',
      'tap vu',
      'bao ve',
      'security guard',
      'tai xe',
      'lai xe',
      'driver',
      'giao hang',
      'shipper',
      'boc xep',
      've sinh cong nghiep',
      'phu kho',
    ],
  },
  {
    code: 'OTHER',
    name: 'Ngành nghề khác',
    keywords: [],
  },
];

/** Mã dùng khi không suy ra được nhóm nào. */
export const OTHER_CODE = 'OTHER';
